import { TProduct } from "@/types";

export const bestSellersData: TProduct[] = [
  {
    id: 9,
    name: "Classic Cotton T-Shirt",
    price: 24.99,
    originalPrice: 39.99,
    rating: 4.9,
    reviews: 1247,
    image: "/bestseller-1.jpg",
    discount: "38% OFF",
    badge: "Best Seller",
  },
  {
    id: 10,
    name: "Premium Polo Shirt",
    price: 49.99,
    originalPrice: 79.99,
    rating: 4.8,
    reviews: 892,
    image: "/bestseller-2.jpg",
    discount: "37% OFF",
    badge: "Best Seller",
  },
  {
    id: 11,
    name: "Striped Casual Shirt",
    price: 44.99,
    originalPrice: 69.99,
    rating: 4.7,
    reviews: 756,
    image: "/bestseller-3.jpg",
    discount: "36% OFF",
    badge: "Best Seller",
  },
  {
    id: 12,
    name: "V-Neck Designer Tee",
    price: 29.99,
    originalPrice: 49.99,
    rating: 4.9,
    reviews: 1089,
    image: "/bestseller-4.jpg",
    discount: "40% OFF",
    badge: "Best Seller",
  },
  {
    id: 13,
    name: "Athletic Performance Shirt",
    price: 39.99,
    originalPrice: 59.99,
    rating: 4.8,
    reviews: 634,
    image: "/bestseller-5.jpg",
    discount: "33% OFF",
    badge: "Best Seller",
  },
  {
    id: 14,
    name: "Vintage Style Tee",
    price: 34.99,
    originalPrice: 54.99,
    rating: 4.6,
    reviews: 521,
    image: "/bestseller-6.jpg",
    discount: "36% OFF",
    badge: "Best Seller",
  },
];
